[workspace]
members = ["expression-js"]

[package]
name = "expression"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
nom-unicode = "0.3.0"
backtrace = "0.3.74"

[profile.dev]
opt-level = 0
debug = "full"